# https://cwiki.apache.org/confluence/display/INFRA/.asf.yaml+features+for+git+repositories

github:
  description: "Theme and sbt-paradox settings used by Pekko projects"
  homepage: https://pekko.apache.org/
  labels:
    - pekko
    - pekko-sbt-paradox
    - paradox
    - sbt
    - themes
    - documentation
    - markdown

  enabled_merge_buttons:
    squash:  true
    merge:   false
    rebase:  true

  protected_branches:
    main: {}
    test:
      required_status_checks:
        # strict means "Require branches to be up to date before merging".
        strict: false
        # contexts are the names of checks that must pass
        contexts:
          - Code is formatted

notifications:
  commits:              commits@pekko.apache.org
  issues:               notifications@pekko.apache.org
  pullrequests:         notifications@pekko.apache.org
  discussions:          notifications@pekko.apache.org

