name: Publish

on:
  push:
    branches: [ "main" ]

jobs:
  sbt:
    name: Publish to apache nexus
    runs-on: ubuntu-20.04
    if: github.repository == 'apache/incubator-pekko-sbt-paradox'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: 0

      - name: Setup Java 8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8

      - name: Cache Coursier cache
        uses: coursier/cache-action@v6

      - name: Publish
        run: |-
          sbt publish
        env:
          NEXUS_USER: ${{ secrets.NEXUS_USER }}
          NEXUS_PW: ${{ secrets.NEXUS_PW }}
